---
rabbitmq_user: test
rabbitmq_password: broiling_algorithm_wireless_galleria  # Consider encrypting this using Ansible Vault
rabbitmq_vhost: /
rabbitmq_configure_priv: .*
rabbitmq_read_priv: .*
rabbitmq_write_priv: .*
rabbitmq_user_tags: administrator
rabbitmq_ports:
  - 5672
  - 15672  # For management UI if needed
