---
- name: Gather system facts for prerequisite checks
  ansible.builtin.setup:
    gather_subset: hardware
  tags:
    - weblogic-prereq-check

- name: Create swap space if needed
  block:
    - name: Check if swap file already exists
      ansible.builtin.stat:
        path: /swapfile
      register: swapfile_stat

    - name: Create swap file
      ansible.builtin.command:
        cmd: fallocate -l 1G /swapfile
        creates: /swapfile
      become: true
      when: not swapfile_stat.stat.exists

    - name: Set swap file permissions
      ansible.builtin.file:
        path: /swapfile
        mode: '0600'
        owner: root
        group: root
      become: true
      when: not swapfile_stat.stat.exists

    - name: Format swap file
      ansible.builtin.command:
        cmd: mkswap /swapfile
      become: true
      register: mkswap_result
      when: not swapfile_stat.stat.exists

    - name: Enable swap file
      ansible.builtin.command:
        cmd: swapon /swapfile
      become: true
      when: 
        - not swapfile_stat.stat.exists
        - mkswap_result is succeeded

    - name: Add swap to fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: '/swapfile none swap sw 0 0'
        state: present
      become: true
      when: not swapfile_stat.stat.exists

    - name: Refresh system facts after swap creation
      ansible.builtin.setup:
        gather_subset: hardware
      when: not swapfile_stat.stat.exists
  when: ansible_swaptotal_mb < 512
  tags:
    - weblogic-prereq-swap

- name: Verify system prerequisites after swap setup
  block:
    - name: Check swap space requirement
      ansible.builtin.debug:
        msg: "Swap space available: {{ ansible_swaptotal_mb }}MB"

    - name: Fail if swap space is still insufficient
      ansible.builtin.fail:
        msg: "Insufficient swap space. Found {{ ansible_swaptotal_mb }}MB, required 512MB minimum"
      when: ansible_swaptotal_mb < 512

    - name: Check temp space
      ansible.builtin.shell: |
        df {{ oracle_temp }} --output=avail --block-size=1M | tail -1
      register: temp_space_check
      changed_when: false

    - name: Verify temp space requirement
      ansible.builtin.fail:
        msg: "Insufficient temp space. Found {{ temp_space_check.stdout }}MB, required 300MB minimum"
      when: temp_space_check.stdout | int < 300
  tags:
    - weblogic-prereq-check

- name: Create Oracle inventory directory
  ansible.builtin.file:
    path: "{{ oracle_base }}/oraInventory"
    state: directory
    owner: "{{ weblogic_user }}"
    group: "{{ weblogic_group }}"
    mode: '0755'
  become: true
  tags:
    - weblogic-inventory-setup

- name: Create oraInst.loc file
  ansible.builtin.copy:
    content: |
      inventory_loc={{ oracle_base }}/oraInventory
      inst_group={{ weblogic_group }}
    dest: /etc/oraInst.loc
    owner: root
    group: "{{ weblogic_group }}"
    mode: '0644'
  become: true
  tags:
    - weblogic-inventory-setup
    
- name: Create WebLogic response file from template
  ansible.builtin.template:
    src: response.rsp.j2
    dest: "{{ oracle_temp }}/weblogic_response.rsp"
    mode: '0600'
    owner: "{{ weblogic_user }}"
    group: "{{ weblogic_group }}"
  tags:
    - weblogic-install-response

- name: Find WebLogic installer jar
  ansible.builtin.find:
    paths: "{{ oracle_temp }}/weblogic_install"
    patterns: "*.jar"
    recurse: true
  register: weblogic_jar
  tags:
    - weblogic-install-find

- name: Install WebLogic Server silently
  ansible.builtin.command:
    cmd: >
      {{ java_home }}/bin/java -jar {{ weblogic_jar.files[0].path }}
      -silent -responseFile {{ oracle_temp }}/weblogic_response.rsp
    creates: "{{ oracle_home }}/wlserver"
  become: true
  become_user: "{{ weblogic_user }}"
  environment:
    JAVA_HOME: "{{ java_home }}"
    ORACLE_BASE: "{{ oracle_base }}"
    ORACLE_HOME: "{{ oracle_home }}"
    TEMP: "{{ oracle_temp }}"
  tags:
    - weblogic-install-silent

- name: Set Oracle environment variables in user profile
  ansible.builtin.blockinfile:
    path: "{{ oracle_base }}/.bashrc"
    create: true
    owner: "{{ weblogic_user }}"
    group: "{{ weblogic_group }}"
    block: |
      # Oracle Environment Variables
      export ORACLE_BASE="{{ oracle_base }}"
      export ORACLE_HOME="{{ oracle_home }}"
      export ORACLE_HOME_OHS="{{ oracle_home_ohs }}"
      export MW_HOME="{{ middleware_home }}"
      export MW_HOME_OHS="{{ middleware_home_ohs }}"
      export WLS_HOME="{{ wls_home }}"
      export WL_HOME="{{ wl_home }}"
      export JAVA_BASE="{{ java_base }}"
      export JAVA_HOME="{{ java_home }}"
      export DOMAIN_BASE="{{ domain_base }}"
      export DOMAIN_HOME="{{ domain_home }}"
      export DOMAIN_HOME_OHS="{{ domain_home_ohs }}"
      export DOMAIN_SHARE="{{ domain_share }}"
      export DOMAIN_APP_HOME="{{ domain_app_home }}"
      export NODEMGR_HOME="{{ nodemgr_home }}"
      export KEYSTR_SHARE="{{ keystr_share }}"
      export LOG_BASE="{{ log_base }}"
      export TEMP="{{ oracle_temp }}"
      export CONFIG_JVM_ARGS="{{ config_jvm_args }}"
      export PATH="{{ oracle_home_ohs }}/oracle_common/jdk/jre/bin:{{ java_home }}/bin:$PATH"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Oracle Environment"
  become: true
  tags:
    - weblogic-install-env

- name: Clean up installation files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ oracle_temp }}/weblogic_install"
    - "{{ oracle_temp }}/weblogic_response.rsp"
    - "{{ oracle_temp }}/{{ weblogic_versions[weblogic_version].installer_name }}"
  tags:
    - weblogic-install-cleanup
