---
- name: Check if WebLogic installer exists in files directory
  ansible.builtin.stat:
    path: "{{ role_path }}/files/weblogic/{{ weblogic_versions[weblogic_version].installer_name }}"
  delegate_to: localhost
  register: weblogic_installer_local
  tags:
    - weblogic-download-check
    - weblogic-files-check

- name: Fail if installer not found in files directory
  ansible.builtin.fail:
    msg: |
      WebLogic installer not found in files directory.
      Please download {{ weblogic_versions[weblogic_version].installer_name }} manually and place it in:
      {{ role_path }}/files/weblogic/{{ weblogic_versions[weblogic_version].installer_name }}
  when: not weblogic_installer_local.stat.exists
  tags:
    - weblogic-download-check

- name: Copy WebLogic installer from files directory
  ansible.builtin.copy:
    src: "weblogic/{{ weblogic_versions[weblogic_version].installer_name }}"
    dest: "{{ oracle_temp }}/{{ weblogic_versions[weblogic_version].installer_name }}"
    owner: "{{ weblogic_user }}"
    group: "{{ weblogic_group }}"
    mode: '0644'
  tags:
    - weblogic-download-installer
    - weblogic-copy-installer

- name: Verify WebLogic installer checksum
  ansible.builtin.stat:
    path: "{{ oracle_temp }}/{{ weblogic_versions[weblogic_version].installer_name }}"
    checksum_algorithm: "{{ weblogic_versions[weblogic_version].checksum.split(':')[0] }}"
  register: installer_checksum
  failed_when: 
    - weblogic_versions[weblogic_version].checksum is defined
    - installer_checksum.stat.checksum != weblogic_versions[weblogic_version].checksum.split(':')[1]
  tags:
    - weblogic-download-verification
    - weblogic-checksum-verification

- name: Create temporary extraction directory
  ansible.builtin.file:
    path: "{{ oracle_temp }}/weblogic_install"
    state: directory
    owner: "{{ weblogic_user }}"
    group: "{{ weblogic_group }}"
    mode: '0755'
  tags:
    - weblogic-download-temp
    - weblogic-preparation

- name: Extract WebLogic installer
  ansible.builtin.unarchive:
    src: "{{ oracle_temp }}/{{ weblogic_versions[weblogic_version].installer_name }}"
    dest: "{{ oracle_temp }}/weblogic_install"
    remote_src: true
    owner: "{{ weblogic_user }}"
    group: "{{ weblogic_group }}"
    creates: "{{ oracle_temp }}/weblogic_install/fmw_{{ weblogic_version }}_wls.jar"
  tags:
    - weblogic-download-extract
    - weblogic-extraction

- name: Verify extraction completed successfully
  ansible.builtin.find:
    paths: "{{ oracle_temp }}/weblogic_install"
    patterns: "*.jar"
  register: extracted_jar_files
  failed_when: extracted_jar_files.matched == 0
  tags:
    - weblogic-download-verification
    - weblogic-extraction-verification

- name: Display installation files summary
  ansible.builtin.debug:
    msg: |
      WebLogic installer processing completed:
      - Source file: {{ weblogic_versions[weblogic_version].installer_name }}
      - Copied to: {{ oracle_temp }}/{{ weblogic_versions[weblogic_version].installer_name }}
      - Extracted to: {{ oracle_temp }}/weblogic_install
      - JAR files found: {{ extracted_jar_files.matched }}
  tags:
    - weblogic-installation-summary
