- name: Check Running services
  ansible.windows.win_shell: |
    Get-CimInstance -Class Win32_Service -Filter "state = 'running'"
  register: script_output
  
- name: Display Script Output
  ansible.builtin.debug:
    var: script_output.stdout