---
# - name: Install Erlang
#   ansible.builtin.dnf:
#     name: https://github.com/rabbitmq/erlang-rpm/releases/download/v26.2.5.3/erlang-26.2.5.3-1.el9.x86_64.rpm
#     state: present
#   tags:
#     - rabbitmq
#     - erlang

- name: Import RabbitMQ signing keys
  ansible.builtin.command:
    cmd: >
      rpm --import https://github.com/rabbitmq/signing-keys/releases/download/3.0/rabbitmq-release-signing-key.asc &&
      rpm --import https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key &&
      rpm --import https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key
  tags:
    - rabbitmq
    - repo
    - gpgkey

- name: Add RabbitMQ and Erlang repository to yum.repos.d
  ansible.builtin.template:
    src: rabbitmq.repo.j2
    dest: /etc/yum.repos.d/rabbitmq.repo
    owner: root
    group: root
    mode: '0644'
  tags:
    - rabbitmq
    - repo

- name: Install RabbitMQ server
  ansible.builtin.dnf:
    name: 
      - socat
      - logrotate
      - erlang
      - rabbitmq-server
    state: present
  tags:
    - rabbitmq
    - install

- name: Start and enable RabbitMQ service
  ansible.builtin.service:
    name: rabbitmq-server
    state: started
    enabled: true
  tags:
    - rabbitmq
    - service

- name: Enable RabbitMQ management plugin
  ansible.builtin.command:
    cmd: rabbitmq-plugins enable rabbitmq_management
  tags:
    - rabbitmq
    - management

- name: Configure RabbitMQ to accept connections
  ansible.builtin.template:
    src: rabbitmq.conf.j2
    dest: /etc/rabbitmq/rabbitmq.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart RabbitMQ
  tags:
    - rabbitmq
    - config

- name: Add RabbitMQ user
  community.rabbitmq.rabbitmq_user:
    user: "{{ rabbitmq_user }}"
    password: "{{ rabbitmq_password }}"
    vhost: "{{ rabbitmq_vhost }}"
    configure_priv: "{{ rabbitmq_configure_priv }}"
    read_priv: "{{ rabbitmq_read_priv }}"
    write_priv: "{{ rabbitmq_write_priv }}"
    tags: "{{ rabbitmq_user_tags }}"
  tags:
    - rabbitmq
    - user

- name: Configure firewall for RabbitMQ
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
  loop: "{{ rabbitmq_ports }}"
  notify: Reload firewall
  tags:
    - rabbitmq
    - firewall