---
- name: Install and configure systems
  hosts: remote
  gather_facts: true
  become: true
  vars_files:
    - vars/main.yml
    - vars/docker.yml

  roles:
    - role: docker
      when: ansible_os_family == "RedHat"
