- name: Perform full patching.
  tags: config
  community.general.pacman:
    update_cache: true
    upgrade: true

- name: Install needed applications using vars.
  tags: config
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - vim
      - git
      - zsh
      - ufw
      - curl
      - wget
      - bash-completion
      - xsel

- name: Generate a random password
  ansible.builtin.set_fact:
    random_password: "{{ lookup('ansible.builtin.password', '/dev/null chars=ascii_letters,digits,punctuation length=24') }}"
  no_log: true

- name: Generate password hash
  ansible.builtin.set_fact:
    user_password_hash: "{{ random_password | password_hash('sha512') }}"
  no_log: true

- name: Add user {{ new_localsystem_arch_new_user }}
  tags: createusers
  ansible.builtin.user:
    name: "{{ new_localsystem_arch_new_user }}"
    shell: /usr/bin/zsh
    home: "/home/{{ new_localsystem_arch_new_user }}"
    password: "{{ user_password_hash }}"
    create_home: true
    state: present
    groups: "{{ user_groups | default([]) }}"
    append: true
    expires: -1
    generate_ssh_key: true
    ssh_key_bits: 4096
    ssh_key_type: rsa
  no_log: true

- name: Save password for later retrieval
  ansible.builtin.copy:
    content: >-
      Password for {{ new_localsystem_arch_ssh_new_user }}: {{ random_password }}
    dest: >-
      /root/{{ new_localsystem_arch_ssh_new_user }}_password_{{
      ansible_date_time.iso8601 | regex_replace('T', '_')
      | regex_replace(':', '-')
      | regex_replace('\\..*', '')
      }}.txt
    mode: '0600'
  no_log: true

- name: Add SSH public key for user {{ new_localsystem_arch_new_user }}.
  tags: createusers
  ansible.posix.authorized_key:
    user: "{{ new_localsystem_arch_new_user }}"
    key: "{{ lookup('file', 'files/id_ed25519.pub') }}"
    state: present

- name: Add sudoer rule for new user.
  tags: createusers
  ansible.builtin.template:
    src: sudoer.j2
    dest: /etc/sudoers.d/{{ new_localsystem_arch_new_user }}
    owner: root
    group: root
    mode: "0440"
    validate: /usr/sbin/visudo -csf %s

- name: Check if .zshrc exists.
  tags: createusers
  ansible.builtin.stat:
    path: /home/{{ new_localsystem_arch_new_user }}/.zshrc
  register: stat_rc_result

- name: Ensure oh-my-zsh is installed
  tags: createusers
  ansible.builtin.git:
    repo: "https://github.com/robbyrussell/oh-my-zsh"
    dest: "/home/{{ new_localsystem_arch_new_user }}/.oh-my-zsh"
    version: "master"
    depth: 1
    force: false
    update: false

- name: Copy .zshrc to home folder.
  tags: createusers
  ansible.builtin.copy:
    dest: /home/{{ new_localsystem_arch_new_user }}/.zshrc
    src: .zshrc
    owner: "{{ new_localsystem_arch_new_user }}"
    group: "{{ new_localsystem_arch_new_user }}"
    mode: "0440"

- name: Ensure zsh-autosuggestions plugin is installed
  tags: createusers
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "/home/{{ new_localsystem_arch_new_user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    version: "master"
    depth: 1
    force: false
    update: false

- name: Set correct ownership for .oh-my-zsh directory
  ansible.builtin.file:
    path: "/home/{{ new_localsystem_arch_new_user }}/.oh-my-zsh"
    owner: "{{ new_localsystem_arch_new_user }}"
    group: "{{ new_localsystem_arch_new_user }}"
    recurse: true
    state: directory

- name: Add hardened SSH config.
  tags: ssh_hardening
  ansible.builtin.copy:
    dest: /etc/ssh/sshd_config
    src: etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0600"
  notify: Reload_sshd

- name: Set a message of the day.
  tags: banners
  ansible.builtin.template:
    dest: /etc/motd
    src: templates/motd.j2
    owner: root
    group: root
    mode: "0644"

- name: Set a login banner.
  tags: banners
  ansible.builtin.copy:
    dest: "{{ item }}"
    src: etc/issue
    owner: root
    group: root
    mode: "0644"
  with_items:
    - /etc/issue.net

- name: Start and enable Firewall Service.
  tags: firewallrules
  ansible.builtin.service:
    name: "{{ firewall_pkg_arch }}"
    enabled: true
    state: started

- name: Allow TCP ports through firewall.
  tags: firewallrules
  community.general.ufw:
    state: enabled
    policy: deny
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "22"

- name: Reboot the server
  tags: rebootsystem
  become: true
  ansible.builtin.reboot:
    msg: "Rebooting server as part of system maintenance"
    pre_reboot_delay: 5
    post_reboot_delay: 30
    reboot_timeout: 600
    test_command: uptime

- name: Check the uptime of the servers
  tags: rebootsystem
  ansible.builtin.command: uptime
  register: uptime_result
  changed_when: false

- name: Display server uptime
  tags: rebootsystem
  ansible.builtin.debug:
    var: uptime_result.stdout
