---
- name: Weblogic installation
  hosts: remote
  become: true
  vars_files:
   - ./vars/main.yml
   - ./vars/users_dict.yml

  pre_tasks:
    - name: install updates (RHEL version 8 and higher)
      when: ansible_distribution_version > '8'
      tags: always
      ansible.builtin.dnf:
        update_only: true
        update_cache: true

    - name: install updates (RHEL version 7.9 and lower)
      when: ansible_distribution_version == '7.9'
      tags: always
      ansible.builtin.dnf:
        update_only: true
        update_cache: true

  tasks:
    - import_tasks: tasks/bootstrap.yml
    - import_tasks: tasks/package.yml
    - import_tasks: tasks/user_group.yml
    - import_tasks: tasks/users.yml
    - import_tasks: tasks/dir_structure.yml
    - import_tasks: tasks/file_structure.yml
    - import_tasks: tasks/update_sysctl.yml
    - import_tasks: tasks/x11.yml
    - import_tasks: tasks/update_jdk_setup.yml