- name: Perform full patching
  ansible.builtin.package:
    name: '*'
    state: latest

- name: Install needed applications using vars.
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - vim
      - zsh
      - git
      - rsyslog
      - yum-utils
      - bash-completion
      - net-tools
      - perl
      - elfutils-libelf-devel
      - tar
      - bzip2
      - bind-utils
      - firewalld
      - dnf-automatic
      - epel-release
      - wget
      - binutils
      - gcc
      - gcc-c++
      - glibc
      - glibc-devel
      - libaio
      - libaio-devel
      - libgcc
      - libstdc++
      - libstdc++-devel
      - libnsl
      - ksh
      - sysstat
      - numactl
      - numactl-devel
      - motif
      - motif-devel
      - redhat-lsb
      - redhat-lsb-core
      - openssl
      - make 
      - xorg-x11-server-utils
      - xorg-x11-xauth
      - xterm
    ignore_errors: true
# User and groups tasks   
- name: Create oinstall group
  group:
    name: oinstall
    gid: 105
    state: present

- name: Add user oracle
  ansible.builtin.user:
    name: oracle
    shell: /bin/bash
    uid: 201
    groups: oinstall
    expires: -1
    home: /home/oracle
    password: $6$28HZxmElEYp37PJD$xNvhxWcMsvFoikTEgQw139A/LZVi.8.Dg3utZrlHbbtTnkYKrk0GmMcwsCqBtwsP/FeKJm9CrWj6OCYEIE3Xs0
    create_home: true
    state: present
# Directory Tasks
- name: Create /home/oracle/dba if it does not exist
  ansible.builtin.file:
    path: /home/oracle/dba
    state: directory
    mode: '0755'
    owner: oracle
    group: oinstall

- name: Create /home/oracle/log if it does not exist
  ansible.builtin.file:
    path: /home/oracle/log
    state: directory
    mode: '0755'
    owner: oracle
    group: oinstall

- name: Create /u01 if it does not exist
  ansible.builtin.file:
    path: /u01
    state: directory
    mode: '0755'
    owner: root
    group: oinstall

- name: Create $LOG_BASE (/u01/logs) if it does not exist
  ansible.builtin.file:
    path: /u01/logs
    state: directory
    mode: '0755'
    owner: oracle
    group: oinstall

- name: Create $ORACLE_BASE (/u01/app/oracle) if it does not exist
  ansible.builtin.file:
    path: /u01/app/oracle
    state: directory
    mode: '0755'
    owner: oracle
    group: oinstall

- name: Create $ORACLE_HOME(/u01/app/oracle/product/{{ oracle_version }}/fmw) if it does not exist
  ansible.builtin.file:
    path: '/u01/app/oracle/product/{{ oracle_version }}/fmw'
    state: directory
    mode: '0755'
    owner: oracle
    group: oinstall

- name: Create $JAVA_BASE (/u01/app/oracle/product/{{ oracle_version }}/fmwjava) if it does not exist
  ansible.builtin.file:
    path: /u01/app/oracle/product/{{ oracle_version }}/fmwjava/
    state: directory
    mode: '0755'
    owner: oracle
    group: oinstall