- name: Perform full patching
  ansible.builtin.package:
    name: '*'
    state: latest

- name: Install needed applications using vars.
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - vim
      - zsh
      - git
      - rsyslog
      - yum-utils
      - bash-completion
      - net-tools
      - perl
      - elfutils-libelf-devel
      - tar
      - bzip2
      - bind-utils
      - firewalld
      - dnf-automatic
      - epel-release
      - wget
      - binutils
      - gcc
      - gcc-c++
      - glibc
      - glibc-devel
      - libaio
      - libaio-devel
      - libgcc
      - libstdc++
      - libstdc++-devel
      - libnsl
      - ksh
      - sysstat
      - numactl
      - numactl-devel
      - motif
      - motif-devel
      - redhat-lsb
      - redhat-lsb-core
      - openssl
      - make 
      - xorg-x11-server-utils
      - xorg-x11-xauth
      - xterm
    ignore_errors: true
# User and groups tasks   
- name: Create oinstall group
  group:
    name: oinstall
    gid: 105
    state: present

- name: Add user oracle
  ansible.builtin.user:
    name: oracle
    shell: /bin/bash
    uid: 201
    groups: oinstall
    expires: -1
    home: /home/oracle
    password: $6$28HZxmElEYp37PJD$xNvhxWcMsvFoikTEgQw139A/LZVi.8.Dg3utZrlHbbtTnkYKrk0GmMcwsCqBtwsP/FeKJm9CrWj6OCYEIE3Xs0
    create_home: true
    state: present