---
# tasks file for common
- name: Update package cache
  ansible.builtin.package:
    update_cache: yes

- name: Upgrade all packages
  ansible.builtin.package:
    name: '*'
    state: latest

- name: Install EPEL repository
  ansible.builtin.package:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"

- name: Install common packages
  ansible.builtin.package:
    name:
      - git
      - git-lfs
      - wget
    state: present

- name: Append Ansible-managed hosts to /etc/hosts
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      # Ansible-managed hosts
      192.168.60.100 ansible-controller.local
      192.168.60.101 mysql.local
      192.168.60.102 memcache.local
      192.168.60.103 rabbitmq.local
      192.168.60.104 tomcat.local
      192.168.60.105 nginx.local
    state: present
    owner: root
    group: root
    mode: '0644'
