---
  - name: install and configure systems
    hosts: remote
    become: true
    roles:
      - { role: debian, when: ansible_os_family == "Debian" }
      - { role: redhat, when: ansible_os_family == "RedHat" }
      - { role: docker, when: ansible_os_family == "RedHat" }
