- name: Reload_ssh
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Reload_sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
