- name: Copy JDK file
  ansible.builtin.copy:
    src: files/u01/app/oracle/product/{{ oracle_version }}/fmwjava/{{ jdk_tarversion }}-linux-x64.tar.gz
    dest: "{{ JAVA_BASE }}/{{ jdk_tarversion }}-linux-x64.tar.gz"
    remote_src: false
    owner: oracle
    group: oinstall

- name: Untar JDK file
  unarchive:
    src: "{{ JAVA_BASE }}/{{ jdk_tarversion }}-linux-x64.tar.gz"
    dest: "{{ JAVA_BASE }}"
    copy: false
    owner: oracle
    group: oinstall

- name: Remove old symlink
  file:
    path: "{{ JAVA_BASE }}/{{ jdk_version }}"
    state: absent

- name: Create symlink for JDK
  become: true
  file:
    src: "{{ JAVA_BASE }}/{{ jdk_version }}_{{ jdk_uversion }}"
    dest: "{{ JAVA_BASE }}/{{ jdk_version }}"
    state: link
    owner: oracle
    group: oinstall
    follow: false

- name: Update securerandom.source property
  lineinfile:
    path: "{{ JAVA_BASE }}/{{ jdk_version }}/jre/lib/security/java.security"
    regex: '^securerandom.source='
    line: 'securerandom.source=file:/dev/./random'
    backup: true