- name: Update sysctl.conf file
  become: true
  block:
    - name: Update or add Oracle Coherence settings in sysctl.conf
      register: syschanged
      ansible.builtin.lineinfile:
        dest: /etc/sysctl.conf
        state: present
        line: "{{ item }}"
      with_items:
        - "net.core.rmem_max=2097152"
        - "net.core.wmem_max=2097152"
      notify: restart_sysctl
