- name: Uncomment or add X11Forwarding line in sshd_config
  register: x11
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: '^#?(X11Forwarding)'
    line: 'X11Forwarding yes'
    backrefs: true
    state: present

- name: Uncomment or add X11DisplayOffset line in sshd_config
  register: x11
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: '^#?(X11DisplayOffset)'
    line: 'X11DisplayOffset 10'
    backrefs: true
    state: present

- name: Uncomment or add X11UseLocalhost line in sshd_config
  register: x11
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: '^#?(X11UseLocalhost)'
    line: 'X11UseLocalhost yes'
    backrefs: true
    state: present

- name: Restart sshd service
  service:
    name: sshd
    state: restarted
  when: x11.changed
