- name: Perform full patching
  ansible.builtin.package:
    name: '*'
    state: latest

- name: Install needed applications using vars.
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - vim
      - zsh
      - git
      - rsyslog
      - bash-completion
      - net-tools
      - perl
      - tar
      - bzip2
      - ufw
      - wget
      - binutils
      - gcc
      - sysstat
      - openssl
      - make 
    ignore_errors: true

# User and groups tasks   
- name: Create oinstall group
  group:
    name: oinstall
    gid: 1005
    state: present

- name: Add user oracle
  ansible.builtin.user:
    name: oracle
    shell: /bin/bash
    uid: 201
    groups: oinstall
    expires: -1
    home: /home/oracle
    password: $6$28HZxmElEYp37PJD$xNvhxWcMsvFoikTEgQw139A/LZVi.8.Dg3utZrlHbbtTnkYKrk0GmMcwsCqBtwsP/FeKJm9CrWj6OCYEIE3Xs0
    create_home: true
    state: present