- name: Perform full patching
  ansible.builtin.package:
    name: '*'
    state: latest

- name: Install needed applications using vars.
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - vim
      - zsh
      - git
      - rsyslog
      - bash-completion
      - net-tools
      - perl
      - tar
      - bzip2
      - ufw
      - wget
      - binutils
      - gcc
      - sysstat
      - openssl
      - make 
    ignore_errors: true
# User and groups tasks   
- name: Create oinstall group
  group:
    name: oinstall
    gid: 1005
    state: present

- name: Add user oracle
  ansible.builtin.user:
    name: oracle
    shell: /bin/bash
    uid: 201
    groups: oinstall
    expires: -1
    home: /home/oracle
    password: $6$28HZxmElEYp37PJD$xNvhxWcMsvFoikTEgQw139A/LZVi.8.Dg3utZrlHbbtTnkYKrk0GmMcwsCqBtwsP/FeKJm9CrWj6OCYEIE3Xs0
    create_home: true
    state: present
# Directory Tasks
- name: Create /home/oracle/dba if it does not exist
  ansible.builtin.file:
    path: /home/oracle/dba
    state: directory
    mode: '0755'
    owner: oracle
    group: oinstall

- name: Create /home/oracle/log if it does not exist
  ansible.builtin.file:
    path: /home/oracle/log
    state: directory
    mode: '0755'
    owner: oracle
    group: oinstall

- name: Create /u01 if it does not exist
  ansible.builtin.file:
    path: /u01
    state: directory
    mode: '0755'
    owner: root
    group: oinstall

- name: Create $LOG_BASE (/u01/logs) if it does not exist
  ansible.builtin.file:
    path: /u01/logs
    state: directory
    mode: '0755'
    owner: oracle
    group: oinstall

- name: Create $ORACLE_BASE (/u01/app/oracle) if it does not exist
  ansible.builtin.file:
    path: /u01/app/oracle
    state: directory
    mode: '0755'
    owner: oracle
    group: oinstall

- name: Create $ORACLE_HOME(/u01/app/oracle/product/{{ oracle_version }}/fmw) if it does not exist
  ansible.builtin.file:
    path: '/u01/app/oracle/product/{{ oracle_version }}/fmw'
    state: directory
    mode: '0755'
    owner: oracle
    group: oinstall

- name: Create $JAVA_BASE (/u01/app/oracle/product/{{ oracle_version }}/fmwjava) if it does not exist
  ansible.builtin.file:
    path: /u01/app/oracle/product/{{ oracle_version }}/fmwjava/
    state: directory
    mode: '0755'
    owner: oracle
    group: oinstall
# Create file structure
- name: Copy .bash_profile file
  template:
    src: templates/bash_profile.j2
    dest: /home/oracle/.bash_profile
    owner: oracle
    group: oracle
    mode: '0644'
- name: Copy .bashrc file
  template:
    src: templates/bashrc.j2
    dest: /home/oracle/.bashrc
    owner: oracle
    group: oracle
    mode: '0644'
- name: Create /etc/oraInst.loc
  lineinfile:
    path: /etc/oraInst.loc
    line: "inventory_loc=/u01/app/oracle/oraInventory"
    create: yes
    owner: oracle
    group: oracle
    mode: '0644'

- name: Add inst_group to /etc/oraInst.loc
  lineinfile:
    path: /etc/oraInst.loc
    line: "inst_group=oinstall"
    insertafter: "inventory_loc=/u01/app/oracle/oraInventory"
    create: no
    owner: oracle
    group: oinstall
    mode: '0644'

# - name: Generate /etc/oraInst.loc
#   template:
#     src: oraInst.loc.j2
#     dest: /etc/oraInst.loc
#     owner: oracle
#     group: oinstall
#     mode: '0644'
- name: Copy 99-oracle.conf to /etc/security/limits.d
  ansible.builtin.copy:
    dest: /etc/security/limits.d/99-oracle.conf
    src: files/etc/security/limits.d/99-oracle.conf
    owner: root
    group: root
    mode: 0640