- name: Perform full patching
  ansible.builtin.package:
    name: '*'
    state: latest

- name: Install needed applications using vars.
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - vim
      - zsh
      - git
      - rsyslog
      - bash-completion
      - net-tools
      - perl
      - tar
      - bzip2
      - ufw
      - wget
      - binutils
      - gcc
      - sysstat
      - openssl
      - make 
    ignore_errors: true
