---
- name: Apply common configuration to all hosts
  hosts: all
  become: true
  roles:
    - common
  tags:
    - common-configuration

- name: Configure and deploy MySQL
  hosts: database
  become: true
  roles:
    - mysql
  tags:
    - mysql

- name: Configure and deploy Memcached
  hosts: memcache
  become: true
  roles:
    - memcache
  tags:
    - memcached

- name: Configure and deploy RabbitMQ
  hosts: rabbitmq
  become: true
  roles:
    - rabbitmq
  tags:
    - rabbitmq

- name: Configure and deploy Tomcat
  hosts: application
  become: true
  roles:
    - tomcat
  tags:
    - tomcat

- name: Configure and deploy Nginx
  hosts: web
  become: true
  roles:
    - nginx
  tags:
    - nginx

- name: Configure and deploy weblogic
  hosts: weblogic
  become: true
  roles:
    - weblogic
  tags:
    - weblogic
